export const WEB3_INITIALIZED = 'WEB3_INITIALIZED';
export const ACCOUNTS_INITIALIZED = 'ACCOUNTS_INITIALIZED';
export const CONTRACTS_INITIALIZED = 'CONTRACTS_INITIALIZED';
export const IPFS_INITIALIZED = 'IPFS_INITIALIZED';
